apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: aksnodepublicipcontroller
  name: aksnodepublicipcontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      run: aksnodepublicipcontroller
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: aksnodepublicipcontroller
    spec:
      containers:
      - image: docker.io/dgkanatsios/aksnodepublicipcontroller:0.2.9
        name: aksnodepublicipcontroller
        volumeMounts:
          - name: akssp
            mountPath: /akssp
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      volumes:
        - name: akssp
          hostPath:
            path: /etc/kubernetes
            type: Directory