---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aksnodepublicipcontroller-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: aksnodepublicipcontroller-rbac
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: aksnodepublicipcontroller-sa
    # Reference to upper's `metadata.namespace`
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: aksnodepublicipcontroller
  name: aksnodepublicipcontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      run: aksnodepublicipcontroller
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: aksnodepublicipcontroller
    spec:
      serviceAccountName: aksnodepublicipcontroller-sa
      containers:
      - image: dgkanatsios/aksnodepublicipcontroller:0.2.9
        name: aksnodepublicipcontroller
        volumeMounts:
          - name: akssp
            mountPath: /akssp
        resources: {}
      volumes:
        - name: akssp
          hostPath:
            path: /etc/kubernetes
            type: Directory